### ISSUE TITLE
about OSDA office-31 class split details

### ISSUE THREAD

**Issue by changwxx** [Solacex/Domain-Consensus-Clustering#10]
According to the paper, Office-31 OSDA class slipt setting is 10/0/11, and the classes are separated according to their alphabetical order. But it seems like there is no released config file for this part, so I am quite confused whether target private 11 refers to class20-30 or class10-20? Many thanks.

**Comment by Solacex** [comment]
https://github.com/Solacex/Domain-Consensus-Clustering/blob/5a626e1a7b294ed8fa71205bbc549a93b566e864/office_run.py#L49
Hello, the classes are separated here, and the original classes are put in the class file list, i.e. dataset/list/office

**Comment by changwxx** [comment]
oh I missed the lines:
https://github.com/Solacex/Domain-Consensus-Clustering/blob/5a626e1a7b294ed8fa71205bbc549a93b566e864/office_run.py#L52-L53
thanks!
