### ISSUE TITLE
Calculation mistake in average of Office-Home OSDA table

### ISSUE THREAD

**Issue by suvaansh** [Solacex/Domain-Consensus-Clustering#16]
Hi @Solacex 
I found a calculation mistake in Table 5 Row4.
The average for Office-Home is coming out as 63.01 whereas it's written as 64.2 in the paper. Kindly rectify this.

I wanted to ask if we should use the correct average when we cite your paper in our new work?

Thanks!

**Comment by Solacex** [comment]
Yes, you can use the corrected average, and I will check and correct it later.

**Comment by suvaansh** [comment]
Thanks!
