### ISSUE TITLE
Incorrect File Name

### ISSUE THREAD

**Issue by suvaansh** [Solacex/Domain-Consensus-Clustering#17]
Kindly rectify the type in the name of the office home run file. It doesn't match with the training command

**Comment by Solacex** [comment]
Which part? the config file? or the run file?

**Comment by suvaansh** [comment]
![image](https://user-images.githubusercontent.com/22363521/168737156-76d8e326-7ac0-4682-907c-ad41af2aab49.png)
This

**Comment by Solacex** [comment]
Thank you for pointing out this!
I have corrected it.
