### ISSUE TITLE
About OSDA setting on office-31

### ISSUE THREAD

**Issue by zzzzzzzzzzzx** [Solacex/Domain-Consensus-Clustering#4]
Hi, i read your code and paper. In the paper, you show the results HM (%) on Office under the OSDA scenario (ResNet-50). However, in the code, the class setting of Office is inconsistent with the previous method such as STA and ROS. In the previous method, the setting of office-31 is 10 known classes and 11 unknown classes. However, in the code, the unknown classes is the left 21 classes. Could u please explain it? Thanks!
![image](https://user-images.githubusercontent.com/44466906/126954386-e305fe09-7006-48f2-bb4a-95a450886af6.png)
![image](https://user-images.githubusercontent.com/44466906/126954425-c0f39837-2615-4a48-ba8a-e10f469db5c7.png)

**Comment by Solacex** [comment]
Thanks for pointing out this mistake, we indeed report the results under the wrong setting, also a more challenging setting. 

I have run the code under the 21-class setting and our method could achieve better results, I will update the new results recently.
However, fortunately,  this will not influence the conclusion in the main paper.

**Comment by zzzzzzzzzzzx** [comment]
: ) Excellent jobs !
