### ISSUE TITLE
Couldn't find requirements.txt file 

### ISSUE THREAD

**Issue by Chloe1997** [Solacex/Domain-Consensus-Clustering#7]
Thanks for sharing your code!
In Prerequisites section, you suggest input this command :pip install -r requirements.txt to install any toolkits needed. However, I could not find  requirements.txt this file in any folder. Where could I find this txt file? 

Many Thanks

**Comment by Solacex** [comment]
Hello,

Thanks for your interest in our work!

I have uploaded the requirements.txt. If you still have any questions, feel free to ask.
