### ISSUE TITLE
If a task with few categories, such as 3 or 4，will the clustering performance be good?

### ISSUE THREAD

**Issue by magnum-zx** [Solacex/Domain-Consensus-Clustering#8]

**Comment by magnum-zx** [comment]
A task with few categories, such as 3 or 4, whether the model will work ?

**Comment by magnum-zx** [comment]
In the code, what is difference between pair_dataset and class_dataset?

**Comment by Solacex** [comment]
Hello, 

1, I cannnot be sure whether this work is applicable on few-class scenarios. 
2, there is no big different two dataset, the class-dataset is with a balanced-sampling.

**Comment by magnum-zx** [comment]
Thank you!
